rsync:
  location: /usr/bin/rsync
  args: -aPhv
snapper:
  enabled: true
  location: /usr/bin/snapper
  cleanup: number

volumes:
  - name: Movies
    src: /mnt/Movies
    dst: /mnt/Movies_backup
  - name: TV Shows
    src: /mnt/TV Shows
    dst: /mnt/TV Shows_backup